name: Ruby

on:
  push:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
      env:
        AWS_ACCESS_KEY_ID: FAKEFAKEFAKEFAKEFAKE
        AWS_SECRET_ACCESS_KEY: fakefakefakefakefakefakefake+fakefakefak
        AWS_REGION: ap-northeast-1
